import { Sequelize, DataTypes } from 'sequelize'
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

export const sequelize = new Sequelize({
  dialect: 'sqlite',
  storage: path.join(__dirname, '../db/matches.sqlite')
});

// model for pending match
export const pendingMatch = sequelize.define('pendingMatch', {
  userName: {
    type: DataTypes.STRING,
    allowNull: false
  },
  difficultyLevel: {
    type: DataTypes.INTEGER,
    allowNull: false
  }
  // createdAt timestamp is generated by default
});

// model for matched users
export const match = sequelize.define('match', {
  firstUser: {
    type: DataTypes.STRING,
    allowNull: false
  },
  secondUser: {
    type: DataTypes.STRING,
    allowNull: false
  },
  roomId: {
    type: DataTypes.STRING,
    allowNull: false
  }
});
